// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrvcqyqvldopdvbnfanz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydmNxeXF2bGRvcGR2Ym5mYW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzEzMDAsImV4cCI6MjA2MTEwNzMwMH0.jf8WQ5O56hi8-5r8Bj1KePz8OJQmD-Ayyoue_jiSxiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);